export interface ApiError {
    message: string
    code: string
    status: number
}

export enum ApiErrorCode {
    // Auth Errors
    INVALID_EMAIL = 'AUTH_001',
    INVALID_PASSWORD_FORMAT = 'AUTH_002',
    INVALID_CREDENTIALS = 'AUTH_003',
    EMAIL_ALREADY_EXISTS = 'AUTH_004',
    EMAIL_NOT_VERIFIED = 'AUTH_005',
    OTP_EXPIRED = 'AUTH_006',
    OTP_INVALID = 'AUTH_007',
    REFRESH_TOKEN_EXPIRED = 'AUTH_008',
    REFRESH_TOKEN_INVALID = 'AUTH_009',
    PASSWORD_LENGTH = 'AUTH_010',
    INVALID_LOGIN_ATTEMPT = 'AUTH_011',
    INVALID_VERIFICATION_ATTEMPT = 'AUTH_012',

    // User Errors
    USER_NOT_FOUND = 'USER_001',
    PASSWORD_SAME_AS_OLD = 'USER_002',
    PASSWORD_CHANGE_TOO_FREQUENT = 'USER_003',
    INCORRECT_CURRENT_PASSWORD = 'USER_004',

    // System Errors
    INTERNAL_ERROR = 'SYS_001',
    DATABASE_ERROR = 'SYS_002',
}